export const MessageType = {
    // my new messages
    SCRAPE_CONTENT_TEXT: 'SCRAPE_CONTENT_TEXT',
    PREPARE: 'PREPARE',
    PREPARATION_DONE: 'PREPARATION_DONE',
    ASK_QUESTION: 'ASK_QUESTION',
    HIGHLIGHT_ANSWER: 'HIGHLIGHT_ANSWER',
    MAKE_ANSWERS_ITERABLE: 'MAKE_ANSWERS_ITERABLE',
    SEARCH_OPERATION_DONE: 'SEARCH_OPERATION_DONE',
    SELECT: 'SELECT',
    CLEAR: 'CLEAR'
  };
